---
- name: Deploy FastApi
  hosts: prod
  become: no

  vars:
    first_deploy: False
    config_files_to_copy:
      - { src: "{{playbook_dir}}/config.yaml", dest: "/app/fastapi/manifest/config/", mode: '0644' }
      - { src: "{{playbook_dir}}/fastapi.service", dest: "/etc/systemd/system/", mode: '0644' }
    bin_files_to_copy:
      - { src: "{{playbook_dir}}/fastapi.tar.gz", dest: "/app/fastapi/bin/", mode: '0755' }
    paths:
      - /app/fastapi/logs/
      - /app/fastapi/resource/

  tasks:
    - name: Create group app
      group:
        name: app
        state: present
      when: first_deploy

    - name: Create user app
      user:
        name: app
        group: app
        state: present
        create_home: yes
        home: /app
      when: first_deploy

    - name: Upload Config Files to Remote
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: app
        group: app
      with_items: "{{ config_files_to_copy }}"
      when: first_deploy

    - name: Upload and Unzip Bin file
      unarchive:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: app
        group: app
        extra_opts:
          - --transform
          - s/^deploy//
      with_items: "{{ bin_files_to_copy }}"

    - name: Create App Running Directory
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        group: app
        owner: app
      with_items: "{{ paths }}"
      when: first_deploy

    - name: Restart FastApi Service
      systemd:
        name: fastapi
        state: restarted
        enabled: yes