---
- name: Deploy FastApi
  hosts: prod
  become: no

  vars:
    files_to_copy:
      - { src: "{{playbook_dir}}/config.yaml", dest: "/app/fastapi/manifest/config/", mode: '0644' }
      - { src: "{{playbook_dir}}/fastapi.service", dest: "/etc/systemd/system/", mode: '0644' }
      - { src: "{{playbook_dir}}/fastapi", dest: "/app/fastapi/bin/", mode: '0755' }
    paths:
      - /app/fastapi/logs/
      - /app/fastapi/resource/

  tasks:
    - name: Create group app
      group:
        name: app
        state: present

    - name: Create user app
      user:
        name: app
        group: app
        state: present
        create_home: yes
        home: /app

    - name: Upload Files to Remote
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: app
        group: app
      with_items: "{{ files_to_copy }}"

    - name: Create App Running Directory
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        group: app
        owner: app
      with_items: "{{ paths }}"

    - name: Restart FastApi Service
      systemd:
        name: fastapi
        state: restarted
        enabled: yes