---
- name: Deploy FastApi
  hosts: prod
  become: no

  vars:
    files_to_copy:
      - { src: "{{playbook_dir}}/config.yaml", dest: "/app/fastapi/manifest/config/", mode: '0644' }
      - { src: "{{playbook_dir}}/fastapi.service", dest: "/etc/systemd/system/", mode: '0644' }
      - { src: "{{playbook_dir}}/fastapi", dest: "/app/fastapi/bin/", mode: '0755' }

  tasks:
    - name: Upload Files to Remote
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      with_items: "{{ files_to_copy }}"

    - name: Create Log Directory
      file:
        path: /app/fastapi/logs
        state: directory
        mode: '0755'

    - name: Restart FastApi Service
      systemd:
        name: fastapi
        state: restarted
        enabled: yes